cache:
  dir: "$HOME/d_cache"
  verbose: 1
  mmap_mode: "c"

timer:
  log_level: "debug"
  key_threshold: 0
  key_interval: 1
  key_frequency: 0
  summary_frequency: 3
  silent: False
  summarize: True
  decay: 0.05

toolz:
  use_cytoolz: False

trial:
  trials_dir: "_trials_dir_"

json:
  use_simplejson: False
